In [1]:
import numpy as np

x1=np.zeros((3,4))
print(x1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
x2=np.ones((3,4))
print(x2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
x3=np.full((2,3),7)
print(x3)

[[7 7 7]
 [7 7 7]]


In [9]:
x4=np.eye(3)
print(x4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a=[20,30,50,100,150]
x5=np.min (a)
print(x5)

x6=np.max(a)
print(x6)


20
150


In [19]:
a=[120,230,345]
b=[234,154,123]
x7=np.add(a,b)
print(x7)

[354 384 468]
