In [2]:
import numpy as np
a=np.array([[8,20,24,25],[30,35,36,40],[42,43,47,50],[49,51,52,53]])
print(a)


[[ 8 20 24 25]
 [30 35 36 40]
 [42 43 47 50]
 [49 51 52 53]]


In [3]:
print(a[1:3,1:3])


[[35 36]
 [43 47]]


In [4]:
print(a[2: ,1:])


[[43 47 50]
 [51 52 53]]


In [5]:
print(a[0:2,2:])

[[24 25]
 [36 40]]


In [7]:
import pandas as pd
x=pd.DataFrame({'rollno':[101,102,103],'name':['ridhi','siddhi','dipti']},index=[0,1,2],columns=("rollno","name"))
print(x)

   rollno    name
0     101   ridhi
1     102  siddhi
2     103   dipti


In [8]:
x.head(2)

rollno    name
0     101   ridhi
1     102  siddhi

In [9]:
x.describe()

rollno
count     3.0
mean    102.0
std       1.0
min     101.0
25%     101.5
50%     102.0
75%     102.5
max     103.0

In [10]:
x.tail(2)

rollno    name
1     102  siddhi
2     103   dipti

In [12]:
x={'rollno':[101,102,103],'name':['dipti','siddhi','riddhi']}
type(x)

dict

In [ ]:
import pandas as pd

In [20]:
df = pd.read_csv("Customer-Churn-Records.csv")
df.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  Complain  Satisfaction Score Card Type  \
0        101348.88       1         1                   2   DIAMOND   
1        112542.58       0         1                   3   DIAMOND   
2        113931.57       1         1                   3   DIAMOND   
3         93826.63       0         0                   5      GOLD   
4         79084.10       0         0                   5      GOLD   

   Point Earned  
0           464  
1           456  
2           377  
3           350  
4           425

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   RowNumber           10000 non-null  int64  
 1   CustomerId          10000 non-null  int64  
 2   Surname             10000 non-null  object 
 3   CreditScore         10000 non-null  int64  
 4   Geography           10000 non-null  object 
 5   Gender              10000 non-null  object 
 6   Age                 10000 non-null  int64  
 7   Tenure              10000 non-null  int64  
 8   Balance             10000 non-null  float64
 9   NumOfProducts       10000 non-null  int64  
 10  HasCrCard           10000 non-null  int64  
 11  IsActiveMember      10000 non-null  int64  
 12  EstimatedSalary     10000 non-null  float64
 13  Exited              10000 non-null  int64  
 14  Complain            10000 non-null  int64  
 15  Satisfaction Score  10000 non-null  int64  
 16  Card 

In [23]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited      Complain  Satisfaction Score  \
count     10000.000000  10000.000000  10000.000000        10000.000000   
mean     100090.239881      0.203800      0.204400            3.013800   
std       57510.492818      0.402842      0.403283            1.405919   
min          11.580000      0.000000      0.000000            1.000000   
25%       51002.110000      0.000000      0.000000            2.000000   
50%      100193.915000      0.000000      0.000000            3.000000   
75%      149388.247500      0.000000      0.000000            4.000000   
max      199992.480000      1.000000      1.000000            5.000000   

       Point Earned  
count  10000.000000  
mean     606.515100  
std      225.924839  
min      119.000000  
25%      410.000000  
50%      605.000000  
75%      801.000000  
max     1000.000000

In [24]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [25]:
df.shape

(10000, 18)

In [26]:
df.columns.names

FrozenList([None])

In [27]:
df.columns.values

array(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain',
       'Satisfaction Score', 'Card Type', 'Point Earned'], dtype=object)

In [28]:
df.dtypes

RowNumber               int64
CustomerId              int64
Surname                object
CreditScore             int64
Geography              object
Gender                 object
Age                     int64
Tenure                  int64
Balance               float64
NumOfProducts           int64
HasCrCard               int64
IsActiveMember          int64
EstimatedSalary       float64
Exited                  int64
Complain                int64
Satisfaction Score      int64
Card Type              object
Point Earned            int64
dtype: object

In [29]:
df.shape

(10000, 18)

In [30]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain',
       'Satisfaction Score', 'Card Type', 'Point Earned'],
      dtype='object')

In [31]:
df.iloc[200]

RowNumber                   201
CustomerId             15604482
Surname               Chiemezie
CreditScore                 850
Geography                 Spain
Gender                     Male
Age                          30
Tenure                        2
Balance               141040.01
NumOfProducts                 1
HasCrCard                     1
IsActiveMember                1
EstimatedSalary          5978.2
Exited                        0
Complain                      0
Satisfaction Score            2
Card Type               DIAMOND
Point Earned                615
Name: 200, dtype: object

In [32]:
df.toss_winner.iloc[200]

<class 'AttributeError'>: 'DataFrame' object has no attribute 'toss_winner'

In [33]:
df.toss_winner.iloc[200]

<class 'AttributeError'>: 'DataFrame' object has no attribute 'toss_winner'